In [1]:
import numpy as np

In [2]:
# set precision
np.set_printoptions(precision=2)

Creating matrix


In [3]:
a=np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [4]:
b=np.array([[1,2,3],[1,2,3]])
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [1 2 3]]
(2, 3)
2


In [5]:
c=np.array([[[1,2],[3,4],[5,6]],[[2,1],[2,3],[4,5]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [3 4]
  [5 6]]

 [[2 1]
  [2 3]
  [4 5]]]
(2, 3, 2)
3


In [6]:
c=np.array([[[[1,2],[1,2],[1,2],[1,2],[1,2],[5,6],[4,5]]],[[[1,2],[1,2],[1,2],[1,2],[1,2],[5,6],[4,5]]]])
print(c)
print(c.shape)
print(c.ndim)

[[[[1 2]
   [1 2]
   [1 2]
   [1 2]
   [1 2]
   [5 6]
   [4 5]]]


 [[[1 2]
   [1 2]
   [1 2]
   [1 2]
   [1 2]
   [5 6]
   [4 5]]]]
(2, 1, 7, 2)
4


-generate matrix
.linear
. random

In [7]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [8]:
a=np.arange(-np.pi, np.pi, .25)
print(a)
a.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [9]:
b=np.linspace(1,10,100)
print(b)
b.shape

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


(100,)

In [10]:
b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [11]:
b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [12]:
b=np.random.rand(3,3)
print(b)

[[0.56 0.37 0.81]
 [0.59 0.58 0.7 ]
 [0.79 0.48 0.43]]


In [13]:
b=np.random.randn(3,3)
print(b)

[[-0.57  1.61 -0.61]
 [ 0.07 -1.73  0.89]
 [ 0.4  -0.29 -1.05]]


In [14]:
d=np.random.randint(1,100,(5,3))
print(d)
d.size

[[17  8 30]
 [76 63 51]
 [41 29 27]
 [ 7 63 10]
 [54 91 13]]


15

In [15]:
d=np.random.randint(1,100,(5,5))
e=np.random.randint(1,100,(5,5))
print(d)
print(e)

[[33 65 63 66 66]
 [98 48 90 49 45]
 [98 65 22 58 65]
 [70 20 92 71  7]
 [76 12 23 57 59]]
[[57  3 75 85 70]
 [14 66 41 98 81]
 [50 23 57 39 47]
 [33 78 80 29 71]
 [69 87 62 20 65]]


In [16]:
d+e

array([[ 90,  68, 138, 151, 136],
       [112, 114, 131, 147, 126],
       [148,  88,  79,  97, 112],
       [103,  98, 172, 100,  78],
       [145,  99,  85,  77, 124]])

In [17]:
d-10

array([[23, 55, 53, 56, 56],
       [88, 38, 80, 39, 35],
       [88, 55, 12, 48, 55],
       [60, 10, 82, 61, -3],
       [66,  2, 13, 47, 49]])

In [18]:
d.dot(e)

array([[12673, 16728, 18103, 14866, 19512],
       [15480, 13269, 21158, 18865, 21382],
       [13995, 15269, 19939, 18540, 21502],
       [11696,  9793, 17428, 13697, 16340],
       [11602, 11128, 15721, 11366, 15255]])

In [30]:
n=np.random.randint(1,100,(6,6))
print(n)

print(n[n>30])

[[13 66 49 21 34 27]
 [23 21 74 59 17 22]
 [71 96 93 86 93 74]
 [13 96 28 84 29 46]
 [85 89 97 52 46 13]
 [ 2 50 42  1 83  8]]
[66 49 34 74 59 71 96 93 86 93 74 96 84 46 85 89 97 52 46 50 42 83]


In [31]:
z=[]
for i in n:
    for j in i:
        if j>30:
            z.append(j)
print(np.array(z))

[66 49 34 74 59 71 96 93 86 93 74 96 84 46 85 89 97 52 46 50 42 83]


In [32]:
print(n[n>30])

[66 49 34 74 59 71 96 93 86 93 74 96 84 46 85 89 97 52 46 50 42 83]


In [34]:
n>30

array([[False,  True,  True, False,  True, False],
       [False, False,  True,  True, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False,  True, False,  True, False,  True],
       [ True,  True,  True,  True,  True, False],
       [False,  True,  True, False,  True, False]])

In [36]:
f=n<40
n[f]

array([13, 21, 34, 27, 23, 21, 17, 22, 13, 28, 29, 13,  2,  1,  8])

In [37]:
n[(n>30) & (n<45)]

array([34, 42])

slicing
1D =[start:stop:end]
2D= [r_start:r_stop:r_step,c_start:c_stop:c_step]

In [38]:
print('first row')
print(n[0])

first row
[13 66 49 21 34 27]


In [39]:
print('last row')
print(n[-1])

last row
[ 2 50 42  1 83  8]


In [40]:
print('slice 2 to 5')
print(n[2:6])

slice 2 to 5
[[71 96 93 86 93 74]
 [13 96 28 84 29 46]
 [85 89 97 52 46 13]
 [ 2 50 42  1 83  8]]


In [41]:
n[:,0]

array([13, 23, 71, 13, 85,  2])

In [42]:
n[:,-1]

array([27, 22, 74, 46, 13,  8])

In [47]:
n[:,-3:]

array([[21, 34, 27],
       [59, 17, 22],
       [86, 93, 74],
       [84, 29, 46],
       [52, 46, 13],
       [ 1, 83,  8]])