In [18]:
import numpy as np

In [19]:
# set precision
np.set_printoptions(precision=2)

Creating matrix


In [20]:
a=np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [21]:
b=np.array([[1,2,3],[1,2,3]])
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [1 2 3]]
(2, 3)
2


In [22]:
c=np.array([[[1,2],[3,4],[5,6]],[[2,1],[2,3],[4,5]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [3 4]
  [5 6]]

 [[2 1]
  [2 3]
  [4 5]]]
(2, 3, 2)
3


In [23]:
c=np.array([[[[1,2],[1,2],[1,2],[1,2],[1,2],[5,6],[4,5]]],[[[1,2],[1,2],[1,2],[1,2],[1,2],[5,6],[4,5]]]])
print(c)
print(c.shape)
print(c.ndim)

[[[[1 2]
   [1 2]
   [1 2]
   [1 2]
   [1 2]
   [5 6]
   [4 5]]]


 [[[1 2]
   [1 2]
   [1 2]
   [1 2]
   [1 2]
   [5 6]
   [4 5]]]]
(2, 1, 7, 2)
4


-generate matrix
.linear
. random

In [24]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [25]:
a=np.arange(-np.pi, np.pi, .25)
print(a)
a.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [28]:
b=np.linspace(1,10,100)
print(b)
b.shape

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


(100,)

In [29]:
b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [30]:
b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [37]:
b=np.random.rand(3,3)
print(b)

[[0.57 0.51 0.9 ]
 [0.96 0.14 0.98]
 [0.46 0.37 0.78]]


In [38]:
b=np.random.randn(3,3)
print(b)

[[-0.61 -0.69 -0.5 ]
 [-0.12  0.75 -0.18]
 [-0.82  0.4  -0.05]]


In [43]:
d=np.random.randint(1,100,(5,3))
print(d)
d.size

[[78 17 66]
 [56 80 62]
 [30 20 28]
 [18 69 78]
 [ 1 63 50]]


15

In [51]:
d=np.random.randint(1,100,(5,5))
e=np.random.randint(1,100,(5,5))
print(d)
print(e)

[[93 15 91 34  7]
 [88 43 94 54 88]
 [34 88 49 65 94]
 [96 26 33 99 42]
 [56 39 22 64 10]]
[[72 84 19 17 64]
 [84 95 38 88 32]
 [82 50 47 26 19]
 [51 16 71 65 66]
 [91 15  7 19 33]]


In [52]:
d+e

array([[165,  99, 110,  51,  71],
       [172, 138, 132, 142, 120],
       [116, 138,  96,  91, 113],
       [147,  42, 104, 164, 108],
       [147,  54,  29,  83,  43]])

In [53]:
d-10

array([[83,  5, 81, 24, -3],
       [78, 33, 84, 44, 78],
       [24, 78, 39, 55, 84],
       [86, 16, 23, 89, 32],
       [46, 29, 12, 54,  0]])

In [54]:
d.dot(e)

array([[17789, 14436,  9077,  7610, 10636],
       [28418, 18361, 12174, 12906, 15262],
       [25727, 16116, 11566, 15607, 13315],
       [20673, 14398, 11686, 12011, 15523],
       [13286, 10683,  8194,  9306,  9804]])